all : install

install : ~/applications/bin/media_functions.sh ~/applications/bin/rvim.sh

~/applications/bin/media_functions.sh: media_functions.sh
		cp media_functions.sh ~/applications/bin/media_functions.sh

~/applications/bin/rvim.sh : rvim.sh
	cp rvim.sh ~/applications/bin/rvim.sh
